-- Applied to the UniSpace Supabase project on 2026-08-20.
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default 'Estudiante', email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.courses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(trim(name)) between 1 and 120), teacher text not null default 'Docente por definir', color text not null default '#6457e8' check (color ~ '^#[0-9A-Fa-f]{6}$'), progress smallint not null default 0 check (progress between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.schedule_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, course_id uuid not null references public.courses(id) on delete cascade, day_of_week smallint not null check (day_of_week between 1 and 7), start_time time not null, end_time time not null, location text not null default 'Sin aula definida', created_at timestamptz not null default now(), check (end_time > start_time));
create index courses_user_id_idx on public.courses(user_id); create index schedule_entries_user_id_idx on public.schedule_entries(user_id); create index schedule_entries_course_id_idx on public.schedule_entries(course_id);
alter table public.profiles enable row level security; alter table public.courses enable row level security; alter table public.schedule_entries enable row level security;
create policy "Users manage own profile" on public.profiles for all using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "Users manage own courses" on public.courses for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own schedule" on public.schedule_entries for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.profiles (id, full_name, email) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', 'Estudiante'), new.email); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
